-- Script generated by USE 2.6.2

!create F1 : Hotel
!set F1.adresse := '1 rue du moulin 25000 Besançon'
!set F1.etageMin := 1
!set F1.etageMax := 14
!create P1 : Personne
!set P1.nom := 'P1'
!set P1.age := 20
!set P1.sexe := SEXE::masculin
!create P2 : Personne
!set P2.nom := 'P2'
!set P2.age := 20
!set P2.sexe := SEXE::feminin
!create P3 : Personne
!set P3.nom := 'P3'
!set P3.age := 20
!set P3.sexe := SEXE::masculin
!create P4 : Personne
!set P4.nom := 'P4'
!set P4.age := 4
!set P4.sexe := SEXE::feminin
!create P5 : Personne
!set P5.nom := 'P5'
!set P5.age := 3
!set P5.sexe := SEXE::masculin
!create Ch1 : Chambre
!set Ch1.etage :=
!set Ch1.numero :=
!set Ch1.nbDeLits :=
!set Ch1.prix :=
!create Ch2 : Chambre
!create Ch3 : Chambre
!create Ch4 : Chambre
!create Ch5 : Chambre
!create Ch6 : Chambre
!create Ch7 : Chambre
!create Ch8 : Chambre
!create Ch9 : Chambre
!create Ch10 : Chambre
!create Ch11 : Chambre
!create Ch12 : Chambre
!create Ch13 : Chambre
!create Ch14 : Chambre
