<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="KaosGoalModel">
    <eClassifiers xsi:type="ecore:EClass" name="GoalModelElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="explanation" ordered="false" unique="false" lowerBound="1" eType="/1/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Objective" abstract="true" eSuperTypes="/0/GoalModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="alternatives" ordered="false" upperBound="-1" eType="/0/Alternative"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="fatherAlternatives" ordered="false" upperBound="-1" eType="/0/Alternative"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="objectiveConflict" ordered="false" upperBound="-1" eType="/0/Objective"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Alternative" eSuperTypes="/0/GoalModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="father" ordered="false" lowerBound="1" eType="/0/Objective"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="refinements" ordered="false" upperBound="-1" eType="/0/Objective"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expectation" ordered="false" upperBound="-1" eType="/0/Expectation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainProperty" ordered="false" upperBound="-1" eType="/0/DomainProperty"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Requirement" eSuperTypes="/0/Objective">
      <eStructuralFeatures xsi:type="ecore:EReference" name="agent" ordered="false" eType="/0/Agent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Goal" eSuperTypes="/0/Objective"/>
    <eClassifiers xsi:type="ecore:EClass" name="Expectation" eSuperTypes="/0/GoalModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="agent" ordered="false" lowerBound="1" eType="/0/Agent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="alternatives" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Alternative"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainProperty" eSuperTypes="/0/GoalModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="alternative" ordered="false" lowerBound="1" upperBound="-1" eType="/0/Alternative"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DomainHypothese" eSuperTypes="/0/DomainProperty"/>
    <eClassifiers xsi:type="ecore:EClass" name="DomainInvariant" eSuperTypes="/0/DomainProperty"/>
    <eClassifiers xsi:type="ecore:EClass" name="Agent" eSuperTypes="/0/GoalModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="requirement" ordered="false" upperBound="-1" eType="/0/Requirement"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="expectation" ordered="false" upperBound="-1" eType="/0/Expectation"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Integer"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
  </ecore:EPackage>
</xmi:XMI>
